apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-1-config
data:
  nginx.conf: |
    server {
    listen 80;
    root /usr/share/nginx/html;

    location / {
               }
    }
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    application: www
spec:
  replicas: 1
  selector:
    matchLabels:
      application: www
  template:
    metadata:
      labels:
        application: www
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nginx-1-config
            mountPath: /etc/nginx/conf.d
          - mountPath: /usr/share/nginx/html
            name: nginx-pvc
      volumes:
        - name: nginx-1-config
          configMap:
            name: nginx-1-config
        - name: nginx-volume
          persistentVolumeClaim:
            claimName: nginx-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: web
spec:
  selector:
    application: www
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
