apiVersion: v1
kind: Secret
metadata:
  name: mysql-password
type: Opaque
data:
  username: cm9vdA==
  password: cGFzU3cwcmQ=
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
spec:
  selector:
    role: server
  ports:
  - port: 3306
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  labels:
    role: client
spec:
  containers:
  - name: mysql-client
    image: 108lirik/mysql-client-git
    command: ["sh", "-c", "tail -f /dev/null"]
    env:
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-password
          key: password
    resources:
      requests:
        cpu: 50m
        memory: 64Mi

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-server
  labels:
    role: server
spec:
  containers:
  - name: mysql-server
    image: mysql:5.6
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-password
          key: password
    ports:
    - containerPort: 3306
      name: mysql
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
